# Generated by Django 3.1.3 on 2020-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0005_auto_20201115_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='story_images'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='picture',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
