# Generated by Django 3.1.3 on 2020-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0006_auto_20201115_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('FN', 'fun'), ('LV', 'love'), ('UE', 'unexpected_end'), ('MY', 'mystery'), ('FT', 'fairy_tail')], default=('FN',), max_length=20),
        ),
    ]
