# Generated by Django 3.1.3 on 2020-11-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0009_auto_20201115_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('FN', 'fun'), ('LV', 'love'), ('UE', 'unexpected-end'), ('MY', 'mystery'), ('FT', 'fairy-tail')], max_length=20),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_app.story')),
            ],
        ),
    ]
