# Generated by Django 3.1.3 on 2020-11-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0010_auto_20201115_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='writer',
        ),
    ]
