# Generated by Django 3.1.3 on 2020-11-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0011_remove_story_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
