# Generated by Django 3.1.3 on 2020-11-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0002_auto_20201122_1336'),
        ('story_app', '0012_delete_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story_auth.writer'),
            preserve_default=False,
        ),
    ]
