# Generated by Django 3.1.3 on 2020-11-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0003_writer_approved'),
        ('story_app', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user_profile',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='story_auth.userprofile'),
            preserve_default=False,
        ),
    ]
