# Generated by Django 3.1.3 on 2020-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0003_writer_approved'),
        ('story_app', '0016_like_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='favorite',
            field=models.ManyToManyField(to='story_auth.UserProfile'),
        ),
    ]
