# Generated by Django 3.1.3 on 2020-11-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0003_writer_approved'),
        ('story_app', '0017_story_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='story_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='story_auth.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
