# Generated by Django 3.1.3 on 2020-12-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0004_auto_20201127_1647'),
        ('story_app', '0022_auto_20201203_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_app.story')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_auth.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='favorites',
        ),

        migrations.AddField(
            model_name='story',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', through='story_app.Favorite',
                                         to='story_auth.UserProfile'),
        ),
    ]
