# Generated by Django 3.1.3 on 2020-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0004_auto_20201127_1647'),
        ('story_app', '0023_auto_20201203_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', through='story_app.Comment', to='story_auth.UserProfile'),
        ),
    ]
