# Generated by Django 3.1.3 on 2020-12-05 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0005_writer_description'),
        ('story_app', '0024_auto_20201203_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_auth.userprofile'),
        ),
    ]
