# Generated by Django 3.1.3 on 2020-12-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_auth', '0004_auto_20201127_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
